// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MissileSimulator_API.Models;

#nullable disable

namespace MissileSimulator_API.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20251229091653_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("MissileSimulator_API.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("HitOdds")
                        .HasColumnType("REAL");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IconX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IconY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Income")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Unlocked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "base",
                            Icon = "Images/mainBase.png",
                            IconX = 30,
                            IconY = 30,
                            Income = 100,
                            Name = "Mainbase",
                            Stage = 1,
                            Type = "base",
                            Unlocked = true
                        },
                        new
                        {
                            Id = 2,
                            Category = "attack",
                            Icon = "Images/missileSilo.png",
                            IconX = 30,
                            IconY = 30,
                            Name = "Missilesilo",
                            Stage = 4,
                            Type = "longrange",
                            Unlocked = false
                        },
                        new
                        {
                            Id = 3,
                            Category = "defense",
                            HitOdds = 0.10000000000000001,
                            Icon = "Images/airDefense.png",
                            IconX = 30,
                            IconY = 30,
                            Name = "Airdefense",
                            Stage = 1,
                            Type = "defense",
                            Unlocked = true
                        });
                });

            modelBuilder.Entity("MissileSimulator_API.Models.Missile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Radius")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Unlocked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warhead")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Missiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ATACMS",
                            Radius = 300,
                            Range = 300000,
                            Stage = 1,
                            Type = "shortrange",
                            Unlocked = true,
                            Warhead = 230
                        },
                        new
                        {
                            Id = 2,
                            Name = "SCUD-B",
                            Radius = 750,
                            Range = 300000,
                            Stage = 2,
                            Type = "shortrange",
                            Unlocked = false,
                            Warhead = 985
                        },
                        new
                        {
                            Id = 3,
                            Name = "Iskander-M",
                            Radius = 450,
                            Range = 500000,
                            Stage = 3,
                            Type = "shortrange",
                            Unlocked = false,
                            Warhead = 600
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tomahawk",
                            Radius = 400,
                            Range = 1600000,
                            Stage = 2,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 450
                        },
                        new
                        {
                            Id = 5,
                            Name = "DF-21",
                            Radius = 1500,
                            Range = 140000,
                            Stage = 3,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 600
                        });
                });

            modelBuilder.Entity("MissileSimulator_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "1234",
                            Role = "admin",
                            Username = "Joshua"
                        },
                        new
                        {
                            Id = 2,
                            Password = "4321",
                            Role = "user",
                            Username = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
