// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MissileSimulator_API.Models;

#nullable disable

namespace MissileSimulator_API.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20251229154259_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("MissileSimulator_API.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("HitOdds")
                        .HasColumnType("REAL");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IconX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IconY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Income")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Unlocked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "base",
                            Icon = "Images/mainBase.png",
                            IconX = 30,
                            IconY = 30,
                            Income = 100,
                            Name = "Mainbase",
                            Stage = 1,
                            Type = "base",
                            Unlocked = true
                        },
                        new
                        {
                            Id = 2,
                            Category = "base",
                            Icon = "Images/factory.png",
                            IconX = 50,
                            IconY = 50,
                            Income = 200,
                            Name = "Factory",
                            Stage = 2,
                            Type = "economy",
                            Unlocked = false
                        },
                        new
                        {
                            Id = 3,
                            Category = "attack",
                            Icon = "Images/shortrangeSilo.png",
                            IconX = 30,
                            IconY = 30,
                            Name = "Shortrange Silo",
                            Stage = 1,
                            Type = "shortrange",
                            Unlocked = true
                        },
                        new
                        {
                            Id = 4,
                            Category = "attack",
                            Icon = "Images/missileSilo.png",
                            IconX = 30,
                            IconY = 30,
                            Name = "Missilesilo",
                            Stage = 4,
                            Type = "longrange",
                            Unlocked = false
                        },
                        new
                        {
                            Id = 5,
                            Category = "defense",
                            HitOdds = 0.10000000000000001,
                            Icon = "Images/airDefense.png",
                            IconX = 30,
                            IconY = 30,
                            Name = "Airdefense",
                            Stage = 1,
                            Type = "defense",
                            Unlocked = true
                        },
                        new
                        {
                            Id = 6,
                            Category = "defense",
                            HitOdds = 0.02,
                            Icon = "Images/missileDefense.png",
                            IconX = 30,
                            IconY = 30,
                            Name = "Missiledefense",
                            Stage = 4,
                            Type = "defense",
                            Unlocked = false
                        });
                });

            modelBuilder.Entity("MissileSimulator_API.Models.Marker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveGameId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SaveGameId");

                    b.ToTable("Markers");
                });

            modelBuilder.Entity("MissileSimulator_API.Models.Missile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Radius")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Unlocked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warhead")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Missiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ATACMS",
                            Radius = 300,
                            Range = 300000,
                            Stage = 1,
                            Type = "shortrange",
                            Unlocked = true,
                            Warhead = 230
                        },
                        new
                        {
                            Id = 2,
                            Name = "Iskander-M",
                            Radius = 450,
                            Range = 500000,
                            Stage = 2,
                            Type = "shortrange",
                            Unlocked = false,
                            Warhead = 600
                        },
                        new
                        {
                            Id = 3,
                            Name = "SCUD-B",
                            Radius = 750,
                            Range = 300000,
                            Stage = 1,
                            Type = "shortrange",
                            Unlocked = false,
                            Warhead = 985
                        },
                        new
                        {
                            Id = 4,
                            Name = "Trident II D5",
                            Radius = 150,
                            Range = 12000000,
                            Stage = 1,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 450
                        },
                        new
                        {
                            Id = 5,
                            Name = "Minuteman III",
                            Radius = 200,
                            Range = 13000000,
                            Stage = 2,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 300
                        },
                        new
                        {
                            Id = 6,
                            Name = "SS-27",
                            Radius = 200,
                            Range = 11000000,
                            Stage = 3,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 1200
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tomahawk",
                            Radius = 400,
                            Range = 1600000,
                            Stage = 4,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 450
                        },
                        new
                        {
                            Id = 8,
                            Name = "DF-21",
                            Radius = 1500,
                            Range = 140000,
                            Stage = 5,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 600
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hwasong-15",
                            Radius = 300,
                            Range = 13000000,
                            Stage = 6,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 1000
                        },
                        new
                        {
                            Id = 10,
                            Name = "Hwasong-17",
                            Radius = 300,
                            Range = 15000000,
                            Stage = 7,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 2000
                        },
                        new
                        {
                            Id = 11,
                            Name = "Agni-V",
                            Radius = 300,
                            Range = 500000,
                            Stage = 8,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 1500
                        },
                        new
                        {
                            Id = 12,
                            Name = "RS-24 Yars",
                            Radius = 300,
                            Range = 12000000,
                            Stage = 9,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 1500
                        },
                        new
                        {
                            Id = 13,
                            Name = "DF-41",
                            Radius = 300,
                            Range = 15000000,
                            Stage = 10,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 2500
                        },
                        new
                        {
                            Id = 14,
                            Name = "DF-5A",
                            Radius = 500,
                            Range = 13000000,
                            Stage = 11,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 3000
                        },
                        new
                        {
                            Id = 15,
                            Name = "RS-28 Sarmat",
                            Radius = 5000,
                            Range = 18000000,
                            Stage = 12,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 10000
                        },
                        new
                        {
                            Id = 16,
                            Name = "R-36M2 Voyevoda",
                            Radius = 500,
                            Range = 16000000,
                            Stage = 13,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 8800
                        },
                        new
                        {
                            Id = 17,
                            Name = "AN602",
                            Radius = 35000,
                            Range = 20000000,
                            Stage = 14,
                            Type = "longrange",
                            Unlocked = false,
                            Warhead = 57000
                        });
                });

            modelBuilder.Entity("MissileSimulator_API.Models.SaveGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongrangeStage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Money")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShortrangeStage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SaveGames");
                });

            modelBuilder.Entity("MissileSimulator_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "1234",
                            Role = "admin",
                            Username = "Joshua"
                        },
                        new
                        {
                            Id = 2,
                            Password = "4321",
                            Role = "user",
                            Username = "User"
                        });
                });

            modelBuilder.Entity("MissileSimulator_API.Models.Marker", b =>
                {
                    b.HasOne("MissileSimulator_API.Models.SaveGame", "SaveGame")
                        .WithMany("Markers")
                        .HasForeignKey("SaveGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaveGame");
                });

            modelBuilder.Entity("MissileSimulator_API.Models.SaveGame", b =>
                {
                    b.HasOne("MissileSimulator_API.Models.User", "User")
                        .WithOne("SaveGame")
                        .HasForeignKey("MissileSimulator_API.Models.SaveGame", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MissileSimulator_API.Models.SaveGame", b =>
                {
                    b.Navigation("Markers");
                });

            modelBuilder.Entity("MissileSimulator_API.Models.User", b =>
                {
                    b.Navigation("SaveGame")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
